apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.demo.yml convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
  namespace: kqueen
spec:
  type: NodePort
  ports:
  - name: "5080"
    port: 5080
    targetPort: 5080
    nodePort: 30580
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}
