## Defualt values for running etcd as-single-chart
## NOTE: In case of change, refer all changes to kqueen-parent chart.
## For simple using, do not touch it, just use parent values.yml
global:
  etcdHostname: etcd
replicas: 1 #
antiAffinity: "soft" # or "hard"

peerPort: 2380
clientPort: 4001
clientToken: etcd-cluster-1

image:
  repository: quay.io/coreos/
  name: etcd
  tag: v3.3.9
  pullPolicy: IfNotPresent

persistence:
  type: PersistentVolumeClaim # allowed options [emptyDir, hostPath]
  storageProvisioner: gce # allowed options [gce, openstack]
  volumeSize: 10Gi
  hostPath: ""

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 4
  #  memory: 10Gi
