kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-os-kqueen
provisioner: kubernetes.io/cinder
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-os-kqueen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # pass here the size of the volume
  storageClassName: sc-os-kqueen
