replicas: 1 #
antiAffinity: "soft" # or "hard"
deploymentNamespace: kqueen # run 'kubectl create ns kqueen' before

peerPort: 2380
clientPort: 4001
clientToken: etcd-cluster-1

image:
  repository: quay.io/coreos/
  name: etcd
  tag: v3.3.9
  pullPolicy: IfNotPresent

persistence:
  type: PersistentVolumeClaim # allowed options [emptyDir, hostPath]
  storageProvisioner: openstack # allowed options [gce]
  volumeSize: 10Gi
  hostPath: ""

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 4
  #  memory: 10Gi
