apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.demo.yml convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mail
  name: mail
  namespace: kqueen
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mail
    spec:
      containers:
      - env:
        - name: MYHOSTNAME
          value: mail
        image: modularitycontainers/postfix
        name: mail
        resources: {}
      restartPolicy: Always
status: {}
