apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ template "kqueen-chart.name" . }}
    chart: {{ template "kqueen-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.uiService.type }}
  ports:
    - port: {{ .Values.uiService.port }}
      targetPort: {{ .Values.uiPort }}
  selector:
    app: {{ template "kqueen-chart.name" . }}
    release: {{ .Release.Name }}
